/**
 * Generated by Lovrabet CLI v2.3.2
 * Created: 07-10-2026, 15:32:00
 * Page: application-detail
 *
 * @modified 2026-07-10 新增 CPO 单据专用详情页
 */
/**
 * title: 单据 360
 */
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { flushSync } from "react-dom";
import {
  Alert,
  Button,
  Dropdown,
  Empty,
  Modal,
  Space,
  Spin,
  Typography,
  message,
} from "antd";
import type { MenuProps } from "antd";
import {
  EditOutlined,
  PrinterOutlined,
  ReloadOutlined,
  UploadOutlined,
} from "@ant-design/icons";
import { useNavigate, useParams } from "react-router-dom";
import PageScaffold from "@/components/page-scaffold/PageScaffold";
import ApplicationDetailView from "@/features/cpo-application-detail/ApplicationDetailView";
import ApplicationDetailPrintView from "@/features/cpo-application-detail/ApplicationDetailPrintView";
import type { ApplicationDetailPrintMode } from "@/features/cpo-application-detail/ApplicationDetailPrintView";
import { printInStandaloneWindow } from "@/features/cpo-application-detail/print-window";
import { getApplicationDetail } from "@/features/cpo-application-detail/api";
import { APPLICATION_DETAIL_CONFIG } from "@/features/cpo-application-detail/config";
import { formatDateValue } from "@/features/cpo-application-detail/format";
import { lovrabetClient } from "@/api/client";
import IssuedInvoiceUploadDrawer from "@/features/invoice-application/IssuedInvoiceUploadDrawer";
import {
  parseApplicationDetailParams,
  type ApplicationDetailResponse,
} from "@/features/cpo-application-detail/types";
import { $i18n } from "@/i18n";
import styles from "@/features/cpo-application-detail/ApplicationDetailView.module.css";

const t = (key: string, fallbackText: string) => $i18n.t(key, fallbackText);

function detailErrorMessage(error: unknown) {
  const message = error instanceof Error ? error.message : String(error || "");
  if (message.includes("CPO_READ_FORBIDDEN"))
    return t("applicationDetail.errorForbidden", "无权查看该单据");
  if (message.includes("BIZ_NOT_FOUND"))
    return t("applicationDetail.errorNotFound", "未找到该单据");
  return message || t("applicationDetail.errorLoadFailed", "加载单据详情失败");
}

const ApplicationDetailPage: React.FC = () => {
  const navigate = useNavigate();
  const params = useParams();
  const parsed = useMemo(
    () => parseApplicationDetailParams(params.bizType, params.id),
    [params.bizType, params.id],
  );
  const [detail, setDetail] = useState<ApplicationDetailResponse>();
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [printMode, setPrintMode] =
    useState<ApplicationDetailPrintMode>("summary");
  const [invoiceUploadOpen, setInvoiceUploadOpen] = useState(false);
  const printDocumentRef = useRef<HTMLDivElement>(null);

  const loadDetail = useCallback(async () => {
    if (!parsed.ok) return;
    setLoading(true);
    setErrorMessage("");
    try {
      const result = await getApplicationDetail(parsed.bizType, parsed.bizId);
      setDetail(result);
    } catch (error) {
      setDetail(undefined);
      setErrorMessage(detailErrorMessage(error));
    } finally {
      setLoading(false);
    }
  }, [parsed]);

  useEffect(() => {
    void loadDetail();
  }, [loadDetail]);

  useEffect(() => {
    document.body.classList.add("application-detail-page");
    return () => document.body.classList.remove("application-detail-page");
  }, []);

  const config = parsed.ok
    ? APPLICATION_DETAIL_CONFIG[parsed.bizType]
    : undefined;
  const status = detail?.summary.status || String(detail?.biz.status || "");
  const canEdit = parsed.ok && ["draft", "rejected"].includes(status);
  const editPath =
    parsed.ok &&
    parsed.bizType === "invoice" &&
    detail?.biz.invoice_direction === "incoming"
      ? `/invoice-archive-form?id=${parsed.bizId}`
      : parsed.ok && config
        ? config.editPath(parsed.bizId)
        : "";
  const title =
    detail?.summary.title ||
    (config
      ? t("applicationDetail.configTitle", `${config.label}详情`).replace(
          "{label}",
          config.label,
        )
      : t("applicationDetail.defaultTitle", "单据详情"));
  const canUploadIssuedInvoice = Boolean(
    parsed.ok &&
    parsed.bizType === "invoice_application" &&
    status === "reviewed" &&
    detail?.management?.capabilities?.includes(
      "invoice_application_completion",
    ),
  );

  const registerPrintEvent = useCallback(
    async (event: "request" | "confirm", mode: ApplicationDetailPrintMode) => {
      if (!parsed.ok) return;
      await lovrabetClient.bff.execute({
        scriptName: "cpoRegisterApplicationPrint",
        params: {
          bizType: parsed.bizType,
          bizId: parsed.bizId,
          event,
          printMode: mode,
        },
      });
    },
    [parsed],
  );

  const confirmPhysicalPrint = (mode: ApplicationDetailPrintMode) => {
    Modal.confirm({
      title: t(
        "applicationDetail.printConfirmTitle",
        "纸质文件是否已实际打印？",
      ),
      content: t(
        "applicationDetail.printConfirmContent",
        "本次操作将记录在系统操作日志中。浏览器无法判断打印机是否成功出纸，请核对纸质文件后再确认。",
      ),
      okText: t("applicationDetail.printConfirmOk", "确认已打印"),
      cancelText: t("applicationList.printConfirmCancel", "暂不确认"),
      onOk: async () => {
        await registerPrintEvent("confirm", mode);
        message.success(
          t("applicationDetail.printConfirmed", "打印记录已确认"),
        );
      },
    });
  };

  const printDetail = (mode: ApplicationDetailPrintMode) => {
    const targetWindow = window.open(
      "",
      "_blank",
      "popup=yes,width=1000,height=900",
    );
    if (!targetWindow) {
      message.warning(
        t(
          "applicationDetail.popupBlocked",
          "浏览器阻止了打印窗口，请允许本站打开新窗口后重试",
        ),
      );
      return;
    }
    flushSync(() => setPrintMode(mode));
    const sourceElement = printDocumentRef.current?.querySelector<HTMLElement>(
      '[data-application-detail-print-view="true"]',
    );
    if (!sourceElement) {
      targetWindow.close();
      message.error(
        t(
          "applicationDetail.printNotReady",
          "打印内容尚未准备完成，请稍后重试",
        ),
      );
      return;
    }
    void printInStandaloneWindow({
      targetWindow,
      sourceElement,
      title: `${title} - ${
        mode === "summary"
          ? t("applicationDetail.printModeSummary", "财务审批摘要")
          : t("applicationDetail.printModeFull", "完整归档件")
      }`,
      beforePrint: async () => {
        await registerPrintEvent("request", mode);
      },
      onAfterPrint: () => confirmPhysicalPrint(mode),
    }).catch((error) => {
      targetWindow.close();
      message.error(
        t(
          "applicationDetail.printLoadFailed",
          `打印窗口加载失败：${error instanceof Error ? error.message : String(error)}`,
        ).replace(
          "{reason}",
          error instanceof Error ? error.message : String(error),
        ),
      );
    });
  };

  const printMenu: MenuProps = {
    items: [
      {
        key: "full",
        label: t("applicationDetail.printFull", "打印完整归档件"),
      },
    ],
    onClick: ({ key }) => {
      printDetail(key as ApplicationDetailPrintMode);
    },
  };

  return (
    <div ref={printDocumentRef} className={styles.printDocument}>
      <div className={styles.screenDocument}>
        <PageScaffold
          maxWidth={config?.maxWidth || 1320}
          title={
            <div className={styles.pageTitle}>
              <Typography.Title level={3} className={styles.pageTitleText}>
                {title}
              </Typography.Title>
            </div>
          }
          description={
            parsed.ok
              ? detail?.summary.updatedAt
                ? t(
                    "applicationDetail.lastUpdated",
                    `最近更新 ${formatDateValue(detail.summary.updatedAt, true)}`,
                  ).replace(
                    "{time}",
                    formatDateValue(detail.summary.updatedAt, true),
                  )
                : t("applicationDetail.defaultTitle", "单据详情")
              : undefined
          }
          variant="detail"
          density="compact"
          headerExtra={
            <Space className={styles.headerActions} size={8} wrap>
              <Dropdown.Button
                menu={printMenu}
                disabled={!detail || loading}
                onClick={() => printDetail("summary")}
              >
                <PrinterOutlined />
                {t("applicationDetail.printSummary", "打印一页摘要")}
              </Dropdown.Button>
              {canEdit && editPath ? (
                <Button
                  icon={<EditOutlined />}
                  onClick={() => navigate(editPath)}
                >
                  {t("common.edit", "编辑")}
                </Button>
              ) : null}
              {canUploadIssuedInvoice ? (
                <Button
                  type="primary"
                  icon={<UploadOutlined />}
                  onClick={() => setInvoiceUploadOpen(true)}
                >
                  上传已开具发票
                </Button>
              ) : null}
              {parsed.ok ? (
                <Button
                  icon={<ReloadOutlined />}
                  loading={loading}
                  onClick={loadDetail}
                >
                  {t("common.refresh", "刷新")}
                </Button>
              ) : null}
            </Space>
          }
        >
          {!parsed.ok ? (
            <Alert
              type="warning"
              showIcon
              message={"message" in parsed ? parsed.message : ""}
            />
          ) : null}

          {parsed.ok && errorMessage ? (
            <Alert
              type="warning"
              showIcon
              message={errorMessage}
              action={
                <Button size="small" loading={loading} onClick={loadDetail}>
                  {t("applicationDetail.retry", "重试")}
                </Button>
              }
            />
          ) : null}

          {parsed.ok ? (
            <Spin spinning={loading}>
              {!detail && !loading && !errorMessage ? (
                <Empty
                  description={t("applicationDetail.empty", "未找到单据详情")}
                />
              ) : null}
              {detail ? (
                <ApplicationDetailView
                  detail={detail}
                  bizType={parsed.bizType}
                  onWorkflowChanged={loadDetail}
                />
              ) : null}
            </Spin>
          ) : null}
        </PageScaffold>
        {detail && parsed.ok && parsed.bizType === "invoice_application" ? (
          <IssuedInvoiceUploadDrawer
            open={invoiceUploadOpen}
            detail={detail}
            onClose={() => setInvoiceUploadOpen(false)}
            onCompleted={loadDetail}
          />
        ) : null}
      </div>
      {detail && parsed.ok ? (
        <ApplicationDetailPrintView
          detail={detail}
          bizType={parsed.bizType}
          mode={printMode}
        />
      ) : null}
    </div>
  );
};

ApplicationDetailPage.displayName = "单据 360";

export default ApplicationDetailPage;
