/**
 * Generated by Rabetbase CLI
 * Created: 2026-08-11T10:44:11.932Z
 *
 * 这个文件包含了项目的模型配置，并自动注册到 SDK 中
 * CLI 工具会自动维护这个文件，通常不需要手动修改
 */

import { registerModels, CONFIG_NAMES, type ModelsConfig } from "@lovrabet/sdk";

export const LOVRABET_APP_CODE = "app-4d050189";

/**
 * 项目的模型配置
 * 使用数组格式，每个模型包含 datasetCode、tableName、name 和可选的 alias
 *
 * 访问方式：
 * - 标准访问：client.models.dataset_[datasetCode]
 * - 别名访问：client.models.[alias]（如果配置了 alias）
 */
export const LOVRABET_MODELS_CONFIG: ModelsConfig = {
  appCode: LOVRABET_APP_CODE,
  models: [
    {
      datasetCode: "68c70907e27c481cbefb96dd3906936e",
      tableName: "business_partner",
      name: "业务伙伴",
      alias: "businessPartner",
    },
    {
      datasetCode: "1a4139b6d59a493ea89111d936e27238",
      tableName: "biz_relation",
      name: "业务关联",
      alias: "bizRelation",
    },
    {
      datasetCode: "ecebe4f9726b46ccb19aaca00aa93dd0",
      tableName: "cpo_dictionary",
      name: "业务字典",
      alias: "cpoDictionary",
    },
    {
      datasetCode: "65619b5104e44f03b0dcea52b4d8c397",
      tableName: "biz_action_record",
      name: "业务操作记录",
      alias: "bizActionRecord",
    },
    {
      datasetCode: "7da208a5059b4b13896d7c7ae29c8492",
      tableName: "payment_application",
      name: "付款申请",
      alias: "paymentApplication",
    },
    {
      datasetCode: "b4a72c4ca0984102aba03a393063ba65",
      tableName: "company_credential",
      name: "企业资质",
      alias: "companyCredential",
    },
    {
      datasetCode: "28494f18f334400c893576b6e168d3f6",
      tableName: "travel_application",
      name: "出差申请",
      alias: "travelApplication",
    },
    {
      datasetCode: "417122aa7cee4ea78b9acce9c970181c",
      tableName: "legal_agreement_party",
      name: "协议签署方",
      alias: "legalAgreementParty",
    },
    {
      datasetCode: "9dd0d102219145ddbb67d1c247a84fb9",
      tableName: "biz_invoice_link",
      name: "发票关联",
      alias: "bizInvoiceLink",
    },
    {
      datasetCode: "c8962eed35894816b4d7462986037299",
      tableName: "receivable_invoice_allocation",
      name: "发票收款分摊",
      alias: "receivableInvoiceAllocation",
    },
    {
      datasetCode: "fc11e2d760b94b2ca2ccf0485ed40ca8",
      tableName: "invoice_record",
      name: "发票记录",
      alias: "invoiceRecord",
    },
    {
      datasetCode: "08e17d8ba3a24e938fef89816c8f4ccb",
      tableName: "contract_payment_plan",
      name: "合同付款计划",
      alias: "contractPaymentPlan",
    },
    {
      datasetCode: "c4c7c35bfe244a78b08667e649b05640",
      tableName: "crm_contract_receivable_plan",
      name: "合同收款计划",
      alias: "crmContractReceivablePlan",
    },
    {
      datasetCode: "f54c0d114e0b44ea96e8e3754fd1de72",
      tableName: "contract_version",
      name: "合同版本",
      alias: "contractVersion",
    },
    {
      datasetCode: "53869993f80f45ae8ef6cdf051d8e355",
      tableName: "contract_application",
      name: "合同申请",
      alias: "contractApplication",
    },
    {
      datasetCode: "d8e2be71fbf14f93a589ebe96b64e004",
      tableName: "employee",
      name: "员工信息",
      alias: "employee",
    },
    {
      datasetCode: "f6a08809699b437a830fcf96584d834a",
      tableName: "customer_receipt_allocation",
      name: "回款核销分配",
      alias: "customerReceiptAllocation",
    },
    {
      datasetCode: "d980e72f89f54474be37a45d3b563dac",
      tableName: "legacy_approval_archive",
      name: "审批归档",
      alias: "legacyApprovalArchive",
    },
    {
      datasetCode: "c095e4a857dd41bd9ef182617e9d634c",
      tableName: "crm_company",
      name: "客户公司",
      alias: "crmCompany",
    },
    {
      datasetCode: "3397588fc01d446486b72b84960f3059",
      tableName: "customer_receipt",
      name: "客户回款",
      alias: "customerReceipt",
    },
    {
      datasetCode: "3ac96b88e94249efb72f124e6d63a4e4",
      tableName: "crm_customer_status",
      name: "客户状态字典",
      alias: "crmCustomerStatus",
    },
    {
      datasetCode: "da9cddc0fd244545b94ae7cddfde21ea",
      tableName: "biz_task",
      name: "工作流任务",
      alias: "bizTask",
    },
    {
      datasetCode: "d3e59fb7cdf943e8af7e6edee5586cdd",
      tableName: "cpo_workflow_action_config",
      name: "工作流动作配置",
      alias: "cpoWorkflowActionConfig",
    },
    {
      datasetCode: "e541dc67b0b1410998c8c9c645f06f83",
      tableName: "cpo_workflow_step_config",
      name: "工作流步骤配置",
      alias: "cpoWorkflowStepConfig",
    },
    {
      datasetCode: "392bcb15b9124da69bb8329eb5c4ecf2",
      tableName: "invoice_application_fulfillment",
      name: "开票履约关系",
      alias: "invoiceApplicationFulfillment",
    },
    {
      datasetCode: "ab563bb9148947bfb751f8c1aff0d5c7",
      tableName: "internal_legal_entity",
      name: "我方主体",
      alias: "internalLegalEntity",
    },
    {
      datasetCode: "d99c32ef07b749948cc24fd391f8fd2c",
      tableName: "expense_item",
      name: "报销明细项",
      alias: "expenseItem",
    },
    {
      datasetCode: "d60179efd37846e380aafdd166a02871",
      tableName: "expense_rule",
      name: "报销规则",
      alias: "expenseRule",
    },
    {
      datasetCode: "804e3a5ed3224074be329b9ed4799cc3",
      tableName: "crm_contract",
      name: "收款合同",
      alias: "crmContract",
    },
    {
      datasetCode: "4f1b7c4a839f499497fa6a470538738c",
      tableName: "crm_opportunity_contact",
      name: "机会联系人",
      alias: "crmOpportunityContact",
    },
    {
      datasetCode: "32c7c1597ba04cd69ae127b28473f624",
      tableName: "crm_opportunity_stage",
      name: "机会阶段",
      alias: "crmOpportunityStage",
    },
    {
      datasetCode: "afcc8ccb0815418397fcbb5b5682a0c2",
      tableName: "legal_agreement",
      name: "法务协议",
      alias: "legalAgreement",
    },
    {
      datasetCode: "defbf75aee5443768f84debff00a2aa3",
      tableName: "legal_document",
      name: "法务协议文档",
      alias: "legalDocument",
    },
    {
      datasetCode: "4a7c42dba6ff49e48faadcb19165923c",
      tableName: "legal_document_template",
      name: "法务文档模板",
      alias: "legalDocumentTemplate",
    },
    {
      datasetCode: "a2c634ae7c9542c38f0982404dd4b34d",
      tableName: "legal_status_log",
      name: "法务状态日志",
      alias: "legalStatusLog",
    },
    {
      datasetCode: "464ca3622eab43a3a4b4b4f23af26a8c",
      tableName: "cpo_workflow_participant",
      name: "流程参与者",
      alias: "cpoWorkflowParticipant",
    },
    {
      datasetCode: "a7f95d3929fe4c9fa0fb0fd863d1d4e6",
      tableName: "crm_contact",
      name: "联系人",
      alias: "crmContact",
    },
    {
      datasetCode: "19ef166f3d2242a19911ccb8a5685bb8",
      tableName: "salary_payment_item",
      name: "薪资付款明细",
      alias: "salaryPaymentItem",
    },
    {
      datasetCode: "235e11a9cb7945c8926b4d31fe64843f",
      tableName: "salary_payment_application",
      name: "薪资发放申请",
      alias: "salaryPaymentApplication",
    },
    {
      datasetCode: "7851365c96244a1896e834daec447ddb",
      tableName: "expense_application",
      name: "费用报销申请",
      alias: "expenseApplication",
    },
    {
      datasetCode: "ea8bb8be752b4d7685b3e341e559be9f",
      tableName: "crm_follow_up",
      name: "跟进记录",
      alias: "crmFollowUp",
    },
    {
      datasetCode: "07988c72b6754850b85aa75fdbbdb7e4",
      tableName: "crm_opportunity",
      name: "销售机会",
      alias: "crmOpportunity",
    },
    {
      datasetCode: "ae51202c44e140828ba87e4571094d1a",
      tableName: "invoice_application",
      name: "销项开票申请",
      alias: "invoiceApplication",
    },
    {
      datasetCode: "ab17964f0efd46f78cecb4969140f257",
      tableName: "attachment",
      name: "附件管理",
      alias: "attachment",
    },
  ],
} as const;

/**
 * 自动注册配置
 * 配置名称: "app-4d050189"
 */
registerModels(LOVRABET_MODELS_CONFIG, "app-4d050189");

/**
 * 如果需要支持多项目或多环境，可以注册额外的配置：
 *
 * // 开发环境配置
 * registerModels({
 *   appCode: 'app-dev-123',
 *   models: [...]
 * }, 'dev');
 *
 * // 其他项目配置
 * registerModels({
 *   appCode: 'other-project',
 *   models: [...]
 * }, 'project-b');
 */
