/**
 * Lovrabet SDK 客户端实例
 * Generated by Rabetbase CLI
 * Created: 2026-08-11T10:44:11.975Z
 *
 * 这个文件负责创建和导出统一的客户端实例，供整个应用使用
 * 通过导入 './api' 文件来自动执行配置注册
 */

import { createClient, CONFIG_NAMES } from "@lovrabet/sdk";
import "./api"; // 导入配置文件，执行 registerModels() 注册

/**
 * 主要的客户端实例
 * 使用配置名称 '"app-4d050189"' 创建客户端
 */
export const lovrabetClient = createClient({ apiConfigName: "app-4d050189" });

/**
 * 使用示例：
 *
 * // 在组件中使用
 * import { lovrabetClient } from '@/api/client';
 *
 * // 获取数据列表
 * const data = await lovrabetClient.models.businessPartner.getList({
 *   currentPage: 1,
 *   pageSize: 20
 * });
 *
 * // 获取单条记录
 * const record = await lovrabetClient.models.businessPartner.getOne('123');
 *
 * // 创建新记录
 * const newRecord = await lovrabetClient.models.businessPartner.create({
 *   // 记录数据
 * });
 */

/**
 * 其他创建客户端的方式（根据需要选择）：
 *
 * 1. 使用默认配置（无参数调用）：
 * export const lovrabetClient = createClient();
 *
 * 2. 使用其他已注册的配置：
 * export const devClient = createClient('dev');
 * export const prodClient = createClient('prod');
 *
 * 3. 直接传入配置对象：
 * import { LOVRABET_MODELS_CONFIG } from './api';
 * export const lovrabetClient = createClient(LOVRABET_MODELS_CONFIG);
 *
 * 4. 通过 ClientConfig 指定配置名和其他选项：
 * export const lovrabetClient = createClient({
 *   apiConfigName: 'default',
 *   token: 'custom-token',
 *   env: 'daily'
 * });
 *
 * 5. 多项目支持示例：
 * export const projectAClient = createClient('project-a');
 * export const projectBClient = createClient('project-b');
 */
